spring:
  cloud:
    gateway:
      routes:
        - id: users
          uri: http://localhost:8081/users
          predicates:
            - Path=/users/**
        - id: books
          uri: http://localhost:8082/books
          predicates:
            - Path=/books/**