INSERT INTO BOOK VALUES(1, 'TEST-AUTHOR-1', 'TITLE-1');
INSERT INTO BOOK VALUES(2, 'TEST-AUTHOR-2', 'TITLE-2');
INSERT INTO BOOK VALUES(3, 'TEST-AUTHOR-3', 'TITLE-3');
INSERT INTO BOOK VALUES(4, 'TEST-AUTHOR-4', 'TITLE-4');
INSERT INTO BOOK VALUES(5, 'TEST-AUTHOR-5', 'TITLE-5');